[package]
name = "kusama-runtime"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.13", optional = true }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.123", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
static_assertions = "1.1.0"
smallvec = "1.6.1"

authority-discovery-primitives = { package = "sp-authority-discovery", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
offchain-primitives = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
tx-pool-api = { package = "sp-transaction-pool", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
block-builder-api = { package = "sp-block-builder", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }

pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-babe = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-bounties = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-collective = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-democracy = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-identity = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-indices = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-membership = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-nicks = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-offences = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-proxy = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-recovery = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-society = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-staking-reward-curve = { package = "pallet-staking-reward-curve", git = "https://github.com/paritytech/substrate", branch = "kiz-election-provider-2-two-phase-unsigned" }
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-tips = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-utility = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-vesting = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-election-provider-2-two-phase-unsigned" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-offences-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "kiz-election-provider-2-two-phase-unsigned" }
pallet-session-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "kiz-election-provider-2-two-phase-unsigned" }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "kiz-election-provider-2-two-phase-unsigned" }
hex-literal = { version = "0.3.1", optional = true }

runtime-common = { package = "polkadot-runtime-common", path = "../common", default-features = false }
primitives = { package = "polkadot-primitives", path = "../../primitives", default-features = false }

[dev-dependencies]
hex-literal = "0.3.1"
libsecp256k1 = "0.3.5"
tiny-keccak = "2.0.2"
keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate", branch = "kiz-election-provider-2-two-phase-unsigned" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "kiz-election-provider-2-two-phase-unsigned" }
separator = "0.4.1"
serde_json = "1.0.61"

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[features]
default = ["std"]
no_std = []
only-staking = []
std = [
	"authority-discovery-primitives/std",
	"pallet-authority-discovery/std",
	"bitvec/std",
	"primitives/std",
	"rustc-hex/std",
	"parity-scale-codec/std",
	"inherents/std",
	"sp-core/std",
	"sp-api/std",
	"tx-pool-api/std",
	"block-builder-api/std",
	"offchain-primitives/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-collective/std",
	"pallet-elections-phragmen/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-democracy/std",
	"frame-executive/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-nicks/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"pallet-recovery/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-society/std",
	"pallet-staking/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-treasury/std",
	"sp-version/std",
	"pallet-utility/std",
	"pallet-vesting/std",
	"serde_derive",
	"serde/std",
	"log",
	"pallet-babe/std",
	"babe-primitives/std",
	"sp-session/std",
	"pallet-randomness-collective-flip/std",
	"runtime-common/std",
]
runtime-benchmarks = [
	"runtime-common/runtime-benchmarks",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bounties/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-tips/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-offences-benchmarking",
	"pallet-session-benchmarking",
	"frame-system-benchmarking",
	"hex-literal",
]

# When enabled, the runtime api will not be build.
#
# This is required by Cumulus to access certain types of the
# runtime without clashing with the runtime api exported functions
# in WASM.
disable-runtime-api = []
