[package]
name = "polkadot-service"
version = "0.8.3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Substrate Client
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
babe = { package = "sc-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
service = { package = "sc-service", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027", default-features = false }
telemetry = { package = "sc-telemetry", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }

# Substrate Primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
consensus_common = { package = "sp-consensus", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
grandpa_primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }

# Substrate Pallets
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }

# Substrate Other
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "substrate-runtime-dryrun-v027" }

# External Crates
futures = "0.3.8"
hex-literal = "0.3.1"
tracing = "0.1.22"
tracing-futures = "0.2.4"
serde = { version = "1.0.118", features = ["derive"] }

# Polkadot
polkadot-node-core-proposer = { path = "../core/proposer" }
polkadot-overseer = { path = "../overseer" }
polkadot-parachain = { path = "../../parachain" }
polkadot-primitives = { path = "../../primitives" }
polkadot-rpc = { path = "../../rpc" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../subsystem" }
polkadot-node-subsystem-util = { path = "../subsystem-util" }
polkadot-runtime-parachains = { path = "../../runtime/parachains" }

# Polkadot Runtimes
polkadot-runtime = { path = "../../runtime/polkadot" }
kusama-runtime = { path = "../../runtime/kusama" }
westend-runtime = { path = "../../runtime/westend" }
rococo-runtime = { path = "../../runtime/rococo" }

# Polkadot Subsystems
polkadot-availability-bitfield-distribution = { path = "../network/bitfield-distribution", optional = true }
polkadot-availability-distribution = { path = "../network/availability-distribution", optional = true }
polkadot-collator-protocol = { path = "../network/collator-protocol", optional = true }
polkadot-network-bridge = { path = "../network/bridge", optional = true }
polkadot-node-collation-generation = { path = "../collation-generation", optional = true }
polkadot-node-core-av-store = { path = "../core/av-store", optional = true }
polkadot-node-core-backing = { path = "../core/backing", optional = true }
polkadot-node-core-bitfield-signing = { path = "../core/bitfield-signing", optional = true }
polkadot-node-core-candidate-selection = { path = "../core/candidate-selection", optional = true }
polkadot-node-core-candidate-validation = { path = "../core/candidate-validation", optional = true }
polkadot-node-core-chain-api = { path = "../core/chain-api", optional = true }
polkadot-node-core-provisioner = { path = "../core/provisioner", optional = true }
polkadot-node-core-runtime-api = { path = "../core/runtime-api", optional = true }
polkadot-pov-distribution = { path = "../network/pov-distribution", optional = true }
polkadot-statement-distribution = { path = "../network/statement-distribution", optional = true }

[dev-dependencies]
polkadot-test-client = { path = "../test/client" }
env_logger = "0.8.2"

[features]
default = ["db", "full-node"]
db = ["service/db"]
full-node = [
	"polkadot-node-core-av-store",
]
runtime-benchmarks = ["polkadot-runtime/runtime-benchmarks", "kusama-runtime/runtime-benchmarks", "westend-runtime/runtime-benchmarks"]
real-overseer = [
	"polkadot-availability-bitfield-distribution",
	"polkadot-availability-distribution",
	"polkadot-collator-protocol",
	"polkadot-network-bridge",
	"polkadot-node-collation-generation",
	"polkadot-node-core-backing",
	"polkadot-node-core-bitfield-signing",
	"polkadot-node-core-candidate-selection",
	"polkadot-node-core-candidate-validation",
	"polkadot-node-core-chain-api",
	"polkadot-node-core-provisioner",
	"polkadot-node-core-runtime-api",
	"polkadot-pov-distribution",
	"polkadot-statement-distribution",
]
