[package]
name = "polkadot-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
bitvec = { version = "0.8", default-features = false, features = ["alloc"] }
rustc-hex = "1.0"
log = { version = "0.3", optional = true }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false}
polkadot-primitives = { path = "../primitives", default-features = false }
parity-codec = "2.1"
parity-codec-derive = "2.1"
substrate-serializer = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
sr-std = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
sr-io = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-support = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
substrate-client = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
substrate-consensus-aura-primitives = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports", default-features = false }
srml-aura = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-balances = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-consensus = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-council = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-democracy = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-executive = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-grandpa = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-indices = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-session = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-staking = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-sudo = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-system = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-timestamp = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-treasury = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
srml-upgrade-key = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }
sr-version = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }

[dev-dependencies]
hex-literal = "0.1.0"
substrate-keyring = { git = "https://github.com/paritytech/substrate", branch = "alexander-backports" }

[features]
default = ["std"]
std = [
	"bitvec/std",
	"polkadot-primitives/std",
	"parity-codec/std",
	"parity-codec-derive/std",
	"substrate-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-council/std",
	"srml-democracy/std",
	"srml-executive/std",
	"srml-grandpa/std",
	"srml-indices/std",
	"sr-primitives/std",
	"srml-session/std",
	"srml-staking/std",
	"srml-sudo/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-treasury/std",
	"srml-upgrade-key/std",
	"sr-version/std",
	"serde_derive",
	"serde/std",
	"log",
	"safe-mix/std"
]
