[package]
name = "polkadot-statement-table"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "kiz-election-provider-2-two-phase-unsigned" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
