[package]
name = "polkadot-statement-table"
version = "0.8.19"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "ae579a841587919bc12940388e994ef799c37e6c" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
