[package]
name = "polkadot-statement-table"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parity-codec = "~1.0"
parity-codec-derive = "~1.0"
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
polkadot-primitives = { path = "../primitives" }
