[package]
name = "polkadot-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git", branch = "master" }
polkadot-primitives = { path = "../../primitives", default_features = false }
safe-mix = { version = "1.0", default_features = false }
parity-codec = "~2.0.1"
parity-codec-derive = "~2.0.1"
substrate-primitives = { git = "https://github.com/paritytech/substrate", default_features = false }
sr-std = { git = "https://github.com/paritytech/substrate", default_features = false }
sr-io = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-support = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-balances = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-consensus = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-council = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-democracy = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-executive = { git = "https://github.com/paritytech/substrate", default_features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-session = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-staking = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-system = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-timestamp = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-treasury = { git = "https://github.com/paritytech/substrate", default_features = false }
sr-version = { git = "https://github.com/paritytech/substrate", default_features = false }

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
